#Application Name
spring.application.name=AuthenticationService

server.port=8081
jwt.secret=secret
jwttoken.message=Login Successful...

spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://stockmateappdb.cbqqc2ue8xnr.ap-south-1.rds.amazonaws.com/StockMateAppDB?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=26474pal
spring.jpa.hibernate.sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.jpa.repositories.enabled=true
spring.jpa.database=mysql

# Kafka Consumer Configuration
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=group_id
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

springfox.documentation.swagger-ui=/custom-path