#Application Name
spring.application.name=UserProfile

#Using Config Server
#server.port=8083
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=26474pal
#spring.jpa.hibernate.sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.data.jpa.repositories.enabled=true
#spring.jpa.database=mysql

#spring.jpa.show-sql: true

spring.config.import=optional:configserver:http://ec2-3-111-245-16.ap-south-1.compute.amazonaws.com:8888
management.endpoints.web.exposure.include=*

#Kafka Producer Configuration
#spring.kafka.producer.bootstrap-servers= localhost:9092
#spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer

springfox.documentation.swagger-ui=/custom-path
management.security.enabled=false