spring.application.name=config-server
server.port=8888

# Bind the git location to look for the configuration.
spring.cloud.config.server.git.uri=https://github.com/pal-anish/StockMateApp_Config_Properties_AWS
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
management.security.enable=false
management.endpoints.web.exposure.include=*