#Application Name
spring.application.name=WishlistService

server.port=8087

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://stockmateappdb.cbqqc2ue8xnr.ap-south-1.rds.amazonaws.com/StockMateAppDB?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=26474pal
spring.jpa.hibernate.sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.data.jpa.repositories.enabled=true
spring.jpa.database=mysql
springfox.documentation.swagger-ui=/custom-paths3