package com.cts.AuthenticationService.controller;

import com.cts.AuthenticationService.config.JWTTokenGenerator;
import com.cts.AuthenticationService.model.UserCredential;
import com.cts.AuthenticationService.exception.UserNotFoundException;
import com.cts.AuthenticationService.service.UserCredentialService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@EnableDiscoveryClient
@RestController
@CrossOrigin("*")
public class UserCeadentialController {
    private UserCredentialService userCredentialService;
    private JWTTokenGenerator jwtTokenGenerator;
    ResponseEntity<?> responseEntity;

    @Autowired
    public UserCeadentialController(UserCredentialService   userCredentialService,JWTTokenGenerator jwtTokenGenerator) {
        this.userCredentialService = userCredentialService;
        this.jwtTokenGenerator = jwtTokenGenerator;
    }

    @PostMapping("/login")
    public ResponseEntity<?> loginUser(@RequestBody UserCredential userCredential) {
        try{
            if(userCredential.getUsername() == null || userCredential.getPassword() == null) {
                throw  new UserNotFoundException("Username or Password is null");
            }
            UserCredential userDetails = userCredentialService.authenticateUser(userCredential.getUsername(), userCredential.getPassword());
            if(userDetails == null) {
                throw  new UserNotFoundException("User not found");
            }
            if (!(userCredential.getPassword().equals(userDetails.getPassword()))){
                throw  new UserNotFoundException("Password is incorrect");
            }
            /*
             * Create ResponseEntity with token generated by calling generateToken method of JwtTokenGenerator
             */
            responseEntity = new ResponseEntity<>(jwtTokenGenerator.generateToken(userDetails), HttpStatus.OK);

        } catch (UserNotFoundException e) {
            responseEntity = new ResponseEntity<>(e.getMessage(), HttpStatus.UNAUTHORIZED);
        }
        return responseEntity;
    }

}
